[package]
name = "icxtendo/roblox-lua-template"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "lukadev-0/typed-promise@4.0.2"
Fusion = "elttob/fusion@0.2.0"
ProfileService = "aspecky/profileservice@1.0.3"
Trove = "sleitnick/trove@^1.2.0"
Signal = "sleitnick/signal@2.0.1"
String = "robloxiandemo/string@0.1.2"
Reflex = "littensy/reflex@^4.3.1"
Red = "red-blox/red@2.3.0"
RblxUtils = "raphtalia/rbxutils@1.0.0"
WaitFor = "sleitnick/wait-for@1.0.0"
t = "osyrisrblx/t@3.1.1"
Loader = "sleitnick/loader@2.0.0"